### ISSUE TITLE
old url in debian package

### ISSUE THREAD

**Issue by DeeDeeRanged** [kitone/subtitleeditor#11]
Hi,

Just a suggestion. Could you please update the homepage url for the debian stretch (stable) package to http://kitone.github.io/subtitleeditor as the old url is not working anymore.

It will be appreciated by many people I would think.

**Comment by shirishag75** [comment]
@Roesjka it's already been done in unstable/testing. This I guess will be fixed automatically once Buster is released automatically.

**Comment by felagund** [comment]
This has bee nlong since fixed, tahnks for reporting it.
