### ISSUE TITLE
Compiling - enchant dependency not met when enchant-2 is installed 

### ISSUE THREAD

**Issue by vie-des-idees** [kitone/subtitleeditor#13]
Trying to compile last version ( 8a21c6c from 2018-06-25 ) on Manjaro distro (kernel 4.15.18-3-MANJARO), I get the following error
```
checking for GTKMM... yes
checking for ENCHANT... no
configure: error: Package requirements (enchant >= 1.4.0) were not met:

Package 'enchant', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ENCHANT_CFLAGS
and ENCHANT_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
I don't have `*-dev` packages to install as in debian based distros, here are the packages I have available:
```
$ pacman -Ss enchant
extra/enchant 2.2.3-1 [installed]
    A wrapper library for generic spell checking
extra/php-enchant 7.2.8-1
    enchant module for PHP
community/python-gtkspellcheck 4.0.5-4
    Spell-checking library written in Python for Gtk based on Enchant
community/python-pyenchant 2.0.0-2
    PyEnchant is a spellchecking library for Python3 based on the Enchant library
community/python2-gtkspellcheck 4.0.5-4
    Spell-checking library written in Python for Gtk based on Enchant
community/python2-pyenchant 2.0.0-2 [installed]
    PyEnchant is a spellchecking library for Python2 based on the Enchant library
```
So `pkg-config` would be looking for `/usr/lib/pkgconfig/enchant.pc` when what I have is `/usr/lib/pkgconfig/enchant-2.pc` . 

I thought of making symlinks as a workaround, but it sounds a bit messy to me as there might be incompatibility between the major version numbers (I did not check).

Would it be possible to fix the dependency checking itself ? I'm more than rusty in C/CPP programming and don't know much about the autotools. Maybe something like https://github.com/manisandro/qtspell/issues/3 would help  ( [commit 38df124](https://github.com/manisandro/qtspell/commit/38df124263f8a7e46eb580eb502bf7ef3dfebdf3) )

**Comment by kitone** [comment]
Hi,
Could you give me the output of these two commands ?

`pkg-config --modversion enchant`
`pkg-config --modversion enchant-2`

best regards,
kitone

**Comment by vie-des-idees** [comment]
Sure:
```
$ pkg-config --modversion enchant
Package enchant was not found in the pkg-config search path.
Perhaps you should add the directory containing `enchant.pc'
to the PKG_CONFIG_PATH environment variable
Package 'enchant', required by 'virtual:world', not found

$ pkg-config --modversion enchant-2
2.2.3
```

**Comment by kitone** [comment]
Thanks, can you try with the last commit.
