### ISSUE TITLE
Unable to increase the "tempo" of subtitles

### ISSUE THREAD

**Issue by dikonov** [kitone/subtitleeditor#17]
While adapting translations (sound dubbing and subtitles) made for an old DVD to a newer 3D TV rip I had to speed up the sound by 7 seconds throughout the movie. This made the dubbed sound fit well. However, I don't see the option to do the same with the subtitles. I need to shift all subtitles by a variable amount of time that would uniformly increase from 0 to 7,35 seconds towards the end.

Could you add such function if t is not already hiddden there?

**Comment by felagund** [comment]
Timing>Scale does exactly what you need.
