### ISSUE TITLE
Subtitle edit box misplaced when CPL display is on

### ISSUE THREAD

**Issue by apienk** [kitone/subtitleeditor#20]
When the option to display characters per line (CPL) is turned on, the edit box for a subtitle is rendered below the subtitle, which looks confusing and ugly.

**Steps to reproduce:**

1. Uncheck the CPL option (in *Options > Preferences > Interface > Show character per line*).
1. Try editing a subtitle. Everything looks right: cursor is placed inside subtitle and it can be edited where it is.
1. Now, check the CPL option.
1. Try editing a subtitle.

**Observed result:** The subtitle is duplicated just below, obscuring the next subtitle. Cursor is shown in the duplicated box (see attached image below)

![image](https://user-images.githubusercontent.com/9961826/52342939-0e0f2a00-2a17-11e9-8971-bb28201c694a.png)

**Expected result:** Cursor is placed inside the original subtitle for editing.

**Comment by felagund** [comment]
Hm, that sounds likea problem with GTK that was solved some time ago, I think. What distribution are you on and what version of Subtitel Editor do you have?

**Comment by apienk** [comment]
**Ubuntu 16.04.5 LTS**
*subtitleeditor** 0.52.1-2
**libgtk-3-0** 3.18.9-1ubuntu3.3

**Comment by felagund** [comment]
Installing version 54 by compiling from this repository should solve your issue, I think. I am not aware of any packages, I think Ubuntu 18.04 carries a newer version that works. You might try installing packages from 18.04.

Please reopen if that does not help.
