### ISSUE TITLE
trying to install on ubuntu 19.10 error `make: *** No targets specified and no makefile found.  Stop`

### ISSUE THREAD

**Issue by FidelVe** [kitone/subtitleeditor#37]
Hi.

Im trying to install on ubuntu 19.10, the steps I made are as follow:

 `git clone git@github.com:kitone/subtitleeditor.git`
`cd subtitleeditor/`
`./autogen.sh`
`make`

running make gives me the following error:

`make: *** No targets specified and no makefile found.  Stop`

**Comment by nbeaver** [comment]
There is a typo in the readme; it should include the `./configure` command between `./autogen.sh` and `make`. So the full list would be

    git clone git@github.com:kitone/subtitleeditor.git
    cd subtitleeditor/
    ./autogen.sh
    ./configure
    make

More information here:

https://stackoverflow.com/questions/50044091/what-is-the-job-of-autogen-sh-when-building-a-c-package-on-linux

By the way, `subtitleeditor` is in the Ubuntu 19.10 package repository:

https://launchpad.net/ubuntu/eoan/+source/subtitleeditor

so you wouldn't have to build it from source.
