### ISSUE TITLE
Video player in the same window.

### ISSUE THREAD

**Issue by kurotom** [kitone/subtitleeditor#40]
Hello, when opening a video with "subtitleeditor" it does it in a new window, is it possible to attach the video player in the same window as seen in the photo?

Program in Fedora 32.
![Captura de pantalla de 2020-06-24 15-17-03](https://user-images.githubusercontent.com/55354389/85617954-0f51ee80-b62e-11ea-8613-1572797175bf.png)

Desired example.
![unnamed](https://user-images.githubusercontent.com/55354389/85618066-390b1580-b62e-11ea-8a14-31721d57d6e6.png)

I hope some answer.

**Comment by kitone** [comment]
Hi,

You should have an option in the preferences, video player output, you will need to reload a video from file after each change of the option.

Best regards,
